services:
    api:
        build: ./api
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        command: npm run production
        depends_on:
            - mysql
        volumes:
            - ./api:/app
            - whatsapp_auth:/whatsapp/auth
            - node_modules_api:/app/node_modules
        networks:
            - whatsbot
            - default

    web:
        build: ./web
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        command: npm run production
        depends_on:
            - api
        networks:
            - whatsbot
            - default
    mysql:
        image: mysql:8.2
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        env_file:
            - .env
        # ports:
        #     - 127.0.0.1:3309:3306
        volumes:
            # - .:/app
            - mysql:/var/lib/mysql
        networks:
            - default
volumes:
    mysql:
    whatsapp_auth:
    node_modules_api:
    node_modules_web:
networks:
    whatsbot:
        name: whatsbot
    default: