services:
    api:
        build: ./api
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        volumes:
            - ./api:/app
            - whatsapp_auth:/whatsapp/auth
            - node_modules_api:/app/node_modules
        ports:
            - 3000:3000
            - 9229:9229
        command: npm run development
        depends_on:
            - mysql

    web:
        build: ./web
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        volumes:
            - ./web:/app
            - node_modules_web:/app/node_modules
        ports:
            - 80:3000
        command: npm run development
        depends_on:
            - api

    mysql:
        image: mysql:8.2
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - 127.0.0.1:3306:3306
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql:
    whatsapp_auth:
    node_modules_api:
    node_modules_web:
