services:
    api:
        build: ./api
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        command: npm run production
        depends_on:
            - mysql
        volumes:
            - whatsapp_auth:/whatsapp/auth

    web:
        build: ./web
        restart: unless-stopped
        working_dir: /app
        env_file:
            - .env
        command: npm run production
        depends_on:
            - api

    mysql:
        image: mysql:8.2
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql

volumes:
    mysql:
    whatsapp_auth:
